project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "*.ipynb"
    - "!resources*.ipynb"
  resources: CNAME

website:
  page-navigation: true
  title: "CHA Research Design"
  description: "Lecture notes for research design in counseling"

  # site-url:
  # repo-url:
  # repo-actions: [edit, issue]

  page-footer:
    # right: "This page is built with [Quarto](https://quarto.org/)."
    left: This work © 2023 by Sungkyun Cho is licensed under CC BY-NC-SA 4.0 
    # left: "&copy; Copyright 2023, Sungkyun Cho"
    # background: 

  sidebar:
    # background: "#F6F6FF"
    # logo: 
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 3
    
    contents:
      - href: index.qmd
      - href: contents/notice.qmd
      - text: ---
      - section: Notes
        contents:
          - href: contents/overview.ipynb
          - section: Part 2
            contents:
              - section: 5장 관심사와 연구주제
                contents:
                  - href: contents/research-topics.qmd
                    text: 연구 주제
                  - href: contents/research-topics2.qmd
                    text: 가설 개발
              - section: 6장 연구설계의 선택
                contents:
                  - href: contents/select-design.qmd
                    text: 연구 설계의 기본
                  - href: contents/select-design2.qmd
                    text: 연구 설계의 분류
              - section: contents/validity.qmd
                contents: 
                  - href: contents/validity1.qmd
                    text: 통계적 결론 타당도
                  - href: contents/validity2.qmd
                    text: 내적 타당도
                  - href: contents/validity3.qmd
                    text: 구성 타당도
                  - href: contents/validity4.qmd
                    text: 외적 타당도
              - href: contents/population.qmd
                text: 8장 모집단 문제
              - href: contents/scale.qmd
                text: 10장 척도개발
          - section: Part 3
            contents:
              - href: contents/true-experiments.qmd
                text: 11장 진실험 설계
              - href: contents/quasi-experiments.qmd
                text: 12장 준실험과 종단 설계
              # - href: contents/regression1.ipynb
              #   text: Simple Regression
              # - href: contents/regression2.qmd
              #   contents:
              #     - href: contents/case1.qmd
              #     - href: contents/case2.qmd
              #     - href: contents/case3.qmd
              #     - href: contents/case3_sol.qmd
              #       text: Case Study 3 Sol
              #     - href: contents/case4.qmd
      - text: ---
      - section: Communicate
        contents:
          - href: https://docs.google.com/document/d/1u_ac_TLuJjbgaoxg8c-s9sPNQz5rYiEhmSvsBktn6Xs/edit?usp=sharing
            text: Ask

format:
  html:
    toc: true
    toc-depth: 4
    toc-location: right
    code-fold: false
    code-overflow: scroll
    code-summary: "Show the code"
    theme: [sandstone, theme-light.scss]
    # monofont: 'FiraCode-Light'
    mainfont: "Gowun Batang"
    fontsize: 0.95em
    linestretch: 2
    code-copy: true
    highlight-style: Ayu-light
    link-external-newwindow: true
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Gowun+Batang">
    # css: styles.css